"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "EN" | "HI" | "TA" | "MR" | "TE" | "KN" | "ML" | "GU" | "BN" | "PA" | "UR" | "OD" | "AS" | "SJ" | "AR" | "ZH" | "ES" | "FR" | "DE" | "IT" | "JA" | "KO" | "RU" | "PT" | "TR" | "FA" | "NE" | "SI";

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const enTranslations = {
    "app.title": "Govind's Job Portal",
    "nav.home": "Home",
    "nav.login": "Login",
    "nav.post_resume": "Register for Work",
    "hero.title": "Find Work Near You",
    "hero.subtitle": "Daily wages. Immediate joining. No fees.",
    "hero.mic": "Tap to Speak",
    "voice.listening": "Listening...",
    "hero.search.placeholder": "Job (e.g. Driver, Cook)",
    "hero.location.placeholder": "City or Area",
    "hero.button": "Search Jobs",
    "stats.jobs": "Jobs Posted",
    "stats.hired": "Workers Hired",
    "stats.verified": "Verified",
    "categories.title": "Popular Work",
    "categories.all": "All Jobs",
    "job.new": "New",
    "job.posted": "Posted Recently",
    "job.view": "View Details",
    "job.apply": "Easy Apply",
    "footer.rights": "© 2025 Govind's Worker Portal. All rights reserved.",
    "job.painter": "Painter",
    "job.driver": "Driver",
    "job.helper": "Helper",
    "job.cook": "Cook",
    "job.officeboy": "Office Boy",
    "job.security": "Security Guard",
    "job.maid": "House Maid",
    "reg.title": "Worker Registration",
    "reg.name": "Full Name",
    "reg.phone": "Phone Number",
    "reg.email": "Email Address",
    "reg.skill": "Your Skill",
    "reg.location": "Your Location",
    "reg.submit": "Register Now",
    "reg.success": "Registration Successful!",
    "reg.success_msg": "Your profile has been created. You can now log in to see job assignments.",
    "reg.placeholder.name": "Enter your full name",
    "reg.placeholder.phone": "10-digit mobile number",
    "reg.placeholder.email": "example@mail.com",
    "reg.placeholder.skill": "Select your skill",
    "reg.placeholder.location": "Select location",
    "login.title": "Worker Login",
    "login.identifier": "Phone or Email",
    "login.placeholder": "Enter phone or email",
    "login.submit": "Login Now",
    "login.error": "Phone number or Email not registered!",
    "admin.registeredWorkers": "Registered Workers",
    "admin.name": "Name",
    "admin.role": "Role",
    "admin.location": "Location",
    "admin.status": "Status",
    "admin.action": "Action",
    "admin.assignJob": "Assign Job",
    "admin.unassign": "Unassign",
    "admin.assigned": "Assigned",
    "admin.pending": "Pending",
    "admin.confirmDelete": "Are you sure you want to DELETE this worker? This cannot be undone.",
    "dashboard.title": "Worker Dashboard",
    "dashboard.status": "Application Status",
    "dashboard.hired": "You have been Hired!",
    "dashboard.pending": "Application Pending",
    "dashboard.pending_msg": "Your profile is visible to employers. We will notify you when a job matches your skills.",
    "dashboard.job_details": "Job Details",
    "dashboard.location": "Reporting Location",
    "dashboard.supervisor": "Site Supervisor",
    "dashboard.call_supervisor": "Call Supervisor",
    "dashboard.profile": "Your Profile",
    "dashboard.full_name": "Full Name",
    "dashboard.logout": "Logout",
    "dashboard.back_home": "Back to Home Page",
    "admin.dashboard": "Admin Dashboard",
    "admin.viewSite": "View Site",
    "admin.activeJobs": "Active Job Listings",
    "admin.postJob": "Post New Job",
    "admin.recentListings": "Recent Job Listings",
};

const hiTranslations = {
    "app.title": "गोविंद जॉब पोर्टल",
    "nav.home": "होम",
    "nav.login": "लॉगिन",
    "nav.post_resume": "काम के लिए रजिस्टर करें",
    "hero.title": "अपने पास काम ढूँढें",
    "hero.subtitle": "दैनिक वेतन। तुरंत जॉइनिंग। कोई फीस नहीं।",
    "hero.mic": "बोलने के लिए दबाएं",
    "voice.listening": "सुन रहा हूँ...",
    "hero.search.placeholder": "काम (जैसे ड्राइवर, रसोइया)",
    "hero.location.placeholder": "शहर या इलाका",
    "hero.button": "काम खोजें",
    "stats.jobs": "नौकरियां",
    "stats.hired": "लोगो को काम मिला",
    "stats.verified": "वेरीफाईड",
    "categories.title": "लोकप्रिय काम",
    "categories.all": "सभी काम",
    "job.new": "नया",
    "job.posted": "हाल ही में पोस्ट किया गया",
    "job.view": "विवरण देखें",
    "job.apply": "जल्दी आवेदन करें",
    "footer.rights": "© 2025 गोविंद वर्कर पोर्टल। सर्वाधिकार सुरक्षित।",
    "job.painter": "पेंटर",
    "job.driver": "ड्राइवर",
    "job.helper": "हेल्पर",
    "job.cook": "रसोइया",
    "job.officeboy": "ऑफिस बॉय",
    "job.security": "सुरक्षा गार्ड",
    "job.maid": "घर का काम / बाई",
    "reg.title": "मजदूर पंजीकरण",
    "reg.name": "पूरा नाम",
    "reg.phone": "फ़ोन नंबर",
    "reg.email": "ईमेल पता",
    "reg.skill": "आपका कौशल",
    "reg.location": "आपका स्थान",
    "reg.submit": "अभी पंजीकरण करें",
    "reg.success": "पंजीकरण सफल!",
    "reg.success_msg": "आपका प्रोफाइल बन गया है। अब आप जॉब असाइनमेंट देखने के लिए लॉगिन कर सकते हैं।",
    "reg.placeholder.name": "अपना पूरा नाम दर्ज करें",
    "reg.placeholder.phone": "10-अंकों का मोबाइल नंबर",
    "reg.placeholder.email": "example@mail.com",
    "reg.placeholder.skill": "अपना कौशल चुनें",
    "reg.placeholder.location": "स्थान चुनें",
    "login.title": "श्रमिक लॉगिन",
    "login.identifier": "फ़ोन या ईमेल",
    "login.placeholder": "फ़ोन या ईमेल दर्ज करें",
    "login.submit": "अभी लॉगिन करें",
    "login.error": "फ़ोन नंबर या ईमेल पंजीकृत नहीं है!",
    "admin.registeredWorkers": "पंजीकृत श्रमिक",
    "admin.name": "नाम",
    "admin.role": "भूमिका",
    "admin.location": "स्थान",
    "admin.status": "स्थिति",
    "admin.action": "कार्रवाई",
    "admin.assignJob": "काम सौंपें",
    "admin.unassign": "काम हटाएँ",
    "admin.assigned": "सौंप दिया",
    "admin.pending": "लंबित",
    "admin.confirmDelete": "क्या आप वाकई इस श्रमिक को हटाना चाहते हैं? इसे पूर्ववत नहीं किया जा सकता।",
    "dashboard.title": "श्रमिक डैशबोर्ड",
    "dashboard.status": "आवेदन की स्थिति",
    "dashboard.hired": "आपको काम मिल गया है!",
    "dashboard.pending": "आवेदन लंबित है",
    "dashboard.pending_msg": "आपका प्रोफाइल नियोक्ताओं को दिख रहा है। काम मिलने पर हम आपको सूचित करेंगे।",
    "dashboard.job_details": "काम का विवरण",
    "dashboard.location": "रिपोर्टिंग स्थान",
    "dashboard.supervisor": "साइट सुपरवाइजर",
    "dashboard.call_supervisor": "सुपरवाइजर को कॉल करें",
    "dashboard.profile": "आपका प्रोफाइल",
    "dashboard.full_name": "पूरा नाम",
    "dashboard.logout": "लॉगआउट",
    "dashboard.back_home": "होम पेज पर वापस जाएं",
    "admin.dashboard": "एडमिन डैशबोर्ड",
    "admin.viewSite": "साइट देखें",
    "admin.activeJobs": "सक्रिय नौकरी लिस्टिंग",
    "admin.postJob": "नई नौकरी पोस्ट करें",
    "admin.recentListings": "हाल की नौकरी लिस्टिंग",
};

const mrTranslations = {
    "app.title": "गोविंद जॉब पोर्टल",
    "nav.home": "होम",
    "nav.login": "लॉगिन",
    "nav.post_resume": "कामासाठी नोंदणी करा",
    "hero.title": "तुमच्या जवळ काम शोधा",
    "hero.subtitle": "रोजचा ಪಗಾರ್. त्वरित ज्वाइनिंग. कोणतीही फी नाही.",
    "hero.mic": "बोलण्यासाठी दाबा",
    "voice.listening": "ऐकत आहे...",
    "hero.search.placeholder": "काम (उदा. ड्रಾಯವ್ಹರ್, आचारी)",
    "hero.location.placeholder": "शहर किंवा विभाग",
    "hero.button": "काम शोधा",
    "stats.jobs": "नौकऱ्या",
    "stats.hired": "काम मिळाले",
    "stats.verified": "वेरीफाईड",
    "categories.title": "लोकप्रिय कामे",
    "categories.all": "सर्व कामे",
    "job.new": "नवीन",
    "job.posted": "नुकतेच आलेले",
    "job.view": "माहिती पहा",
    "job.apply": "सोपे अर्ज",
    "footer.rights": "© 2025 गोविंद वर्कर पोर्टल. सर्व हक्क राखीव.",
    "job.painter": "पेंटर",
    "job.driver": "ड्रायव्हर",
    "job.helper": "हेल्पर/मदतनीस",
    "job.cook": "आचारी",
    "job.officeboy": "ऑफिस बॉय",
    "job.security": "सिक्युरिटी गार्ड",
    "job.maid": "घरकाम / बाई",
    "reg.title": "कामगार नोंदणी",
};

const taTranslations = {
    "app.title": "கோவிந்த் வேலை தளம்",
    "nav.home": "முகப்பு",
    "nav.login": "உள்நுழைய",
    "nav.post_resume": "வேலைக்கு பதிவு செய்யுங்கள்",
    "hero.title": "உங்களுக்கு அருகில் வேலை தேடுங்கள்",
    "hero.subtitle": "தினக்கூலி. உடனடி வேலை. கட்டணம் இல்லை.",
    "hero.mic": "பேச தட்டவும்",
    "voice.listening": "கேட்கிறது...",
    "hero.search.placeholder": "வேலை (எ.கா. ஓட்டுநர், சமையல்காரர்)",
    "hero.location.placeholder": "நகரம் அல்லது பகுதி",
    "hero.button": "வேலை தேடு",
    "stats.jobs": "வேலைகள்",
    "stats.hired": "தேர்வு செய்யப்பட்டோர்",
    "stats.verified": "சரிபார்க்கப்பட்டது",
    "categories.title": "பிரபலமான வேலைகள்",
    "categories.all": "அனைத்து வேலைகளும்",
    "job.new": "புதிய",
    "job.posted": "சமீபத்தில் இடப்பட்டது",
    "job.view": "விவரம் பார்",
    "job.apply": "விண்ணப்பிக்கவும்",
    "footer.rights": "© 2025 கோவிந்த் வொர்க்கர் போர்டல். உரிமைகள் பாதுகாக்கப்பட்டவை.",
    "job.painter": "பெயிண்டர்",
    "job.driver": "ஓட்டுநர்",
    "job.helper": "உதவியாளர்",
    "job.cook": "சமையல்காரர்",
    "job.officeboy": "அலுவலக உதவியாளர்",
    "job.security": "காவலாளி",
    "job.maid": "வீட்டு வேலைக்காரி",
    "reg.title": "தொழிலாளர் பதிவு",
    "reg.name": "முழு பெயர்",
    "reg.phone": "தொலைபேசி எண்",
    "reg.email": "மின்னஞ்சல் முகவரி",
    "reg.skill": "உங்கள் திறன்",
    "reg.location": "உங்கள் இருப்பிடம்",
    "reg.submit": "இப்போதே பதிவு செய்யுங்கள்",
    "reg.success": "பதிவு வெற்றிகரமாக முடிந்தது!",
    "reg.success_msg": "உங்கள் சுயவிவரம் உருவாக்கப்பட்டது. வேலை ஒதுக்கீடுகளைப் பார்க்க இப்போது உள்நுழையலாம்.",
    "reg.placeholder.name": "உங்கள் முழு பெயரை உள்ளிடவும்",
    "reg.placeholder.phone": "10 இலக்க மொபைல் எண்",
    "reg.placeholder.email": "example@mail.com",
    "reg.placeholder.skill": "உங்கள் திறனைத் தேர்வுசெய்க",
    "reg.placeholder.location": "இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்",
    "login.title": "தொழிலாளர் உள்நுழைவு",
    "login.identifier": "தொலைபேசி அல்லது மின்னஞ்சல்",
    "login.placeholder": "தொலைபேசி அல்லது மின்னஞ்சலை உள்ளிடவும்",
    "login.submit": "இப்போதே உள்நுழையவும்",
    "login.error": "தொலைபேசி எண் அல்லது மின்னஞ்சல் பதிவு செய்யப்படவில்லை!",
    "admin.registeredWorkers": "பதிவு செய்யப்பட்ட தொழிலாளர்கள்",
    "admin.name": "பெயர்",
    "admin.role": "பணி",
    "admin.location": "இருப்பிடம்",
    "admin.status": "நிலை",
    "admin.action": "செயல்",
    "admin.assignJob": "வேலை ஒதுக்கீடு",
    "admin.unassign": "ஒதுக்கீட்டை நீக்கு",
    "admin.assigned": "ஒதுக்கப்பட்டது",
    "admin.pending": "நிலுவையில்",
    "admin.confirmDelete": "இந்த தொழிலாளரை நீக்க விரும்புகிறீர்களா? இதை மாற்ற முடியாது.",
    "dashboard.title": "தொழிலாளர் டேஷ்போர்டு",
    "dashboard.status": "விண்ணப்ப நிலை",
    "dashboard.hired": "நீங்கள் வேலைக்கு தேர்வு செய்யப்பட்டுள்ளீர்கள்!",
    "dashboard.pending": "விண்ணப்பம் நிலுவையில் உள்ளது",
    "dashboard.pending_msg": "உங்கள் சுயவிவரம் முதலாளிகளுக்குத் தெரியும். வேலை கிடைத்தால் உங்களுக்குத் தெரிவிப்போம்.",
    "dashboard.job_details": "வேலை விவரங்கள்",
    "dashboard.location": "அறிக்கையிடல் இடம்",
    "dashboard.supervisor": "தள மேற்பார்வையாளர்",
    "dashboard.call_supervisor": "மேற்பார்வையாளரை அழைக்கவும்",
    "dashboard.profile": "உங்கள் சுயவிவரம்",
    "dashboard.full_name": "முழு பெயர்",
    "dashboard.logout": "வெளியேறவும்",
    "dashboard.back_home": "முகப்பு பக்கத்திற்குச் செல்லவும்",
    "admin.dashboard": "நிர்வாகத் டேஷ்போர்டு",
    "admin.viewSite": "தளத்தைப் பார்க்கவும்",
    "admin.activeJobs": "செயலில் உள்ள வேலைகள்",
    "admin.postJob": "புதிய வேலையைச் சேர்க்கவும்",
    "admin.recentListings": "சமீபத்திய வேலைகள்",
};

const teTranslations = {
    "app.title": "గోవింద్ జాబ్ పోర్టల్",
    "nav.home": "హోమ్",
    "nav.login": "లాగిన్",
    "nav.post_resume": "పని కోసం నమోదు చేసుకోండి",
    "hero.title": "మీ దగ్గర పని వెతకండి",
    "hero.subtitle": "రోజువారీ వేతనాలు. తక్షణ జాయినింగ్. ఫీజు లేదు.",
    "hero.mic": "మాట్లాడటానికి నొక్కండి",
    "voice.listening": "వినబడుతోంది...",
    "hero.search.placeholder": "పని (ఉదా. డ్రైవర్, వంట మనిషి)",
    "hero.location.placeholder": "నగరం లేదా ప్రాంతం",
    "hero.button": "పని వెతకండి",
    "stats.jobs": "ఉద్యోగాలు",
    "stats.hired": "నియమించుకున్నారు",
    "stats.verified": "వెరిఫైడ్",
    "categories.title": "ప్రసిద్ధ పనులు",
    "categories.all": "అన్ని పనులు",
    "job.new": "కొత్తది",
    "job.posted": "ఇటీవల పోస్ట్ చేయబడింది",
    "job.view": "వివరాలు చూడండి",
    "job.apply": "దరఖాస్తు చేయండి",
    "footer.rights": "© 2025 గోవింద్ వర్కర్ పోర్టల్. అన్ని హక్కులూ ప్రత్యేకించబడ్డాయి.",
    "job.painter": "పెయింటర్",
    "job.driver": "డ్రైవర్",
    "job.helper": "హెల్పర్",
    "job.cook": "వంటవాడు",
    "job.officeboy": "ఆఫీస్ బాయ్",
    "job.security": "సెక్యూరిటీ గార్డ్",
    "job.maid": "ఇంటి పని మనిషి",
    "reg.title": "కార్మికుల నమోదు",
};

const knTranslations = {
    "app.title": "ಗೋವಿಂದ್ ಉದ್ಯೋಗ ಪೋರ್ಟಲ್",
    "nav.home": "ಮುಖಪುಟ",
    "nav.login": " ಲಾಗಿನ್",
    "nav.post_resume": "ಕೆಲಸಕ್ಕಾಗಿ ನೋಂದಾಯಿಸಿ",
    "hero.title": "ನಿಮ್ಮ ಹತ್ತಿರ ಕೆಲಸ ಹುಡುಕಿ",
    "hero.subtitle": "ದೈನಂದಿನ ಸಂಬಳ. ತಕ್ಷಣ ಜಾಯಿನಿಂಗ್. ಯಾವುದೇ ಶುಲ್ಕವಿಲ್ಲ.",
    "hero.mic": "ಮಾತನಾಡಲು ಒತ್ತಿರಿ",
    "voice.listening": "ಕೇಳಿಸುತ್ತಿದೆ...",
    "hero.search.placeholder": "ಕೆಲಸ (ಉದಾ. ಚಾಲಕ, ಅಡುಗೆಯವರು)",
    "hero.location.placeholder": "ನಗರ ಅಥವಾ ಪ್ರದೇಶ",
    "hero.button": "ಕೆಲಸ ಹುಡುಕಿ",
    "stats.jobs": "ಕೆಲಸಗಳು",
    "stats.hired": "ನೇಮಕಗೊಂಡವರು",
    "stats.verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    "categories.title": "ಜನಪ್ರಿಯ ಕೆಲಸಗಳು",
    "categories.all": "ಎಲ್ಲಾ ಕೆಲಸಗಳು",
    "job.new": "ಹೊಸ",
    "job.posted": "ಇತ್ತೀಚೆಗೆ ಹಾಕಲಾಗಿದೆ",
    "job.view": "ವಿವರ ನೋಡಿ",
    "job.apply": "ಅರ್ಜಿ ಹಾಕಿ",
    "footer.rights": "© 2025 ಗೋವಿಂದ್ ವರ್ಕರ್ ಪೋರ್ಟಲ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    "job.painter": "ಪೇಂಟರ್",
    "job.driver": "ಚಾಲಕ (Driver)",
    "job.helper": "ಸಹಾಯಕ (Helper)",
    "job.cook": "ಅಡುಗೆಯವರು",
    "job.officeboy": "ಆಫೀಸ್ ಬಾಯ್",
    "job.security": "ಸೆಕ್ಯೂರಿಟಿ ಗಾರ್ಡ್",
    "job.maid": "ಮನೆ ಕೆಲಸದವರು",
    "reg.title": "ಕೆಲಸಗಾರರ ನೋಂದಣಿ",
    "reg.name": "ಪೂರ್ಣ ಹೆಸರು",
    "reg.phone": "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
    "reg.email": "ಇಮೇಲ್ ವಿಳಾಸ",
    "reg.skill": "ನಿಮ್ಮ ಕೌಶಲ್ಯ",
    "reg.location": "ನಿಮ್ಮ ಸ್ಥಳ",
    "reg.submit": "ಈಗಲೇ ನೋಂದಾಯಿಸಿ",
    "reg.success": "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    "reg.success_msg": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸಲಾಗಿದೆ. ಕೆಲಸದ ನಿಯೋಜನೆಗಳನ್ನು ನೋಡಲು ನೀವು ಈಗ ಲಾಗಿನ್ ಮಾಡಬಹುದು.",
    "reg.placeholder.name": "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    "reg.placeholder.phone": "10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    "reg.placeholder.email": "example@mail.com",
    "reg.placeholder.skill": "ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "reg.placeholder.location": "ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "login.title": "ಕೆಲಸಗಾರರ ಲಾಗಿನ್",
    "login.identifier": "ದೂರವಾಣಿ ಅಥವಾ ಇಮೇಲ್",
    "login.placeholder": "ದೂರವಾಣಿ ಅಥವಾ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    "login.submit": "ಈಗಲೇ ಲಾಗಿನ್ ಮಾಡಿ",
    "login.error": "ದೂರವಾಣಿ ಸಂಖ್ಯೆ ಅಥವಾ ಇಮೇಲ್ ನೋಂದಾಯಿಸಲಾಗಿಲ್ಲ!",
    "admin.registeredWorkers": "ನೋಂದಾಯಿತ ಕೆಲಸಗಾರರು",
    "admin.name": "ಹೆಸರು",
    "admin.role": "ಪಾತ್ರ",
    "admin.location": "ಸ್ಥಳ",
    "admin.status": "ಸ್ಥಿತಿ",
    "admin.action": "ಕ್ರಮ",
    "admin.assignJob": "ಕೆಲಸ ನಿಯೋಜಿಸಿ",
    "admin.unassign": "ನಿಯೋಜನೆ ರದ್ದುಮಾಡಿ",
    "admin.assigned": "ನಿಯೋಜಿಸಲಾಗಿದೆ",
    "admin.pending": "ಬಾಕಿ ಇದೆ",
    "admin.confirmDelete": "ಈ ಕೆಲಸಗಾರನನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ? ಇದನ್ನು ರದ್ದುಗೊಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.",
    "dashboard.title": "ಕೆಲಸಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "dashboard.status": "ಅರ್ಜಿಯ ಸ್ಥಿತಿ",
    "dashboard.hired": "ನಿಮಗೆ ಕೆಲಸ ಸಿಕ್ಕಿದೆ!",
    "dashboard.pending": "ಅರ್ಜಿ ಬಾಕಿ ಇದೆ",
    "dashboard.pending_msg": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಉದ್ಯೋಗದಾತರಿಗೆ ಗೋಚರಿಸುತ್ತದೆ. ಕೆಲಸ ಸಿಕ್ಕಿದಾಗ ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ.",
    "dashboard.job_details": "ಕೆಲಸದ ವಿವರಗಳು",
    "dashboard.location": "ವರದಿಯ ಸ್ಥಳ",
    "dashboard.supervisor": "ಸೈಟ್ ಮೇಲ್ವಿಚಾರಕರು",
    "dashboard.call_supervisor": "ಮೇಲ್ವಿಚಾರಕರಿಗೆ ಕರೆ ಮಾಡಿ",
    "dashboard.profile": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್",
    "dashboard.full_name": "ಪೂರ್ಣ ಹೆಸರು",
    "dashboard.logout": "ಲಾಗ್ ಔಟ್",
    "dashboard.back_home": "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    "admin.dashboard": "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "admin.viewSite": "ಸೈಟ್ ವೀಕ್ಷಿಸಿ",
    "admin.activeJobs": "ಸಕ್ರಿಯ ಕೆಲಸದ ಪಟ್ಟಿಗಳು",
    "admin.postJob": "ಹೊಸ ಕೆಲಸವನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ",
    "admin.recentListings": "ಇತ್ತೀಚಿನ ಕೆಲಸದ ಪಟ್ಟಿಗಳು",
};

const bnTranslations = {
    "app.title": "গোবিন্দ জব পোর্টাল",
    "nav.home": "হোম",
    "nav.login": "লগইন",
    "nav.post_resume": "কাজের জন্য রেজিস্টার করুন",
    "hero.title": "আপনার কাছাকাছি কাজ খুঁজুন",
    "hero.subtitle": "দৈনিক বেতন। অবিলম্বে যোগদান। কোন ফি নেই।",
    "hero.mic": "বলতে ট্যাপ করুন",
    "voice.listening": "শুনছি...",
    "hero.search.placeholder": "কাজ (যেমন ড্রাইভার, রাঁধুনি)",
    "hero.location.placeholder": "শهر বা এলাকা",
    "hero.button": "কাজ খুঁজুন",
    "stats.jobs": "চাকরি",
    "stats.hired": "নিয়োগ পেয়েছে",
    "stats.verified": "যাচাইকৃত",
    "categories.title": "জনপ্রিয় কাজ",
    "categories.all": "সব কাজ",
    "job.new": "নতুন",
    "job.posted": "রিসেণ্টলি পোস্ট করা",
    "job.view": "বিস্তারিত দেখুন",
    "job.apply": "আবেদন করুন",
    "footer.rights": "© 2025 গোবিন্দ ওয়ার্কার পোর্টাল। সর্বস্বত্ব সংরক্ষিত।",
    "job.painter": "পেইন্টার",
    "job.driver": "ড্রাইவர்",
    "job.helper": "হেল্পার",
    "job.cook": "রাঁধুনি",
    "job.officeboy": "অফিস বয়",
    "job.security": "সিকিউরিটি গার্ড",
    "job.maid": "বাড়ির কাজের লোক",
    "reg.title": "শ্রমিক রেজিস্ট্রেশন",
};

const translations: Translations = {
    EN: enTranslations,
    HI: hiTranslations,
    MR: mrTranslations,
    TA: taTranslations,
    TE: teTranslations,
    KN: knTranslations,
    BN: bnTranslations,
    // Add other fallbacks or implement later
    ML: enTranslations, GU: enTranslations, PA: enTranslations, UR: enTranslations,

    OD: enTranslations, AS: enTranslations, SJ: enTranslations, AR: enTranslations,
    ZH: enTranslations, ES: enTranslations, FR: enTranslations, DE: enTranslations,
    IT: enTranslations, JA: enTranslations, KO: enTranslations, RU: enTranslations,
    PT: enTranslations, TR: enTranslations, FA: enTranslations, NE: enTranslations,
    SI: enTranslations,
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    speechCode: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("EN");

    useEffect(() => {
        const saved = localStorage.getItem("app-language") as Language;
        if (saved && translations[saved]) {
            setLanguage(saved);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("app-language", lang);
    };

    const speechCodes: Record<Language, string> = {
        EN: 'en-IN',
        HI: 'hi-IN',
        TA: 'ta-IN',
        MR: 'mr-IN',
        TE: 'te-IN',
        KN: 'kn-IN',
        BN: 'bn-IN',
        ML: 'ml-IN',
        GU: 'gu-IN',
        PA: 'pa-IN',
        UR: 'ur-IN',
        // Fallbacks
        OD: 'en-IN', AS: 'en-IN', SJ: 'en-IN', AR: 'ar-SA', ZH: 'zh-CN', ES: 'es-ES',
        FR: 'fr-FR', DE: 'de-DE', IT: 'it-IT', JA: 'ja-JP', KO: 'ko-KR', RU: 'ru-RU',
        PT: 'pt-PT', TR: 'tr-TR', FA: 'fa-IR', NE: 'ne-NP', SI: 'si-LK'
    };

    const t = (key: string) => {
        const translation = translations[language]?.[key];
        return translation || translations["EN"][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, speechCode: speechCodes[language] }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
